class locator(object):

    landing                             = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[2]"
    register                            = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]"
    popup_register                      = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]"
    reg_name                            = "//input[@id='reg_username']"
    reg_mail                            = "//input[@id='reg_email']"
    reg_pass                            = "//input[@id='reg_password']"
    reg_cnfrmpass                       = "//input[@id='password_conf']"
    reg_execution                       = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/p[2]/button[1]"
    skip                                = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]"
    search                              = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[5]/input[1]"
    quickpass                           = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/section[1]/div[3]/ul[1]/li[6]/a[1]"
    quickpass_pop                       = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/input"

    notification                        = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[2]/div[1]"
    notif_options                       = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[2]"
    accept                              = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[2]/button[1]"
    reject                              = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[2]/button[2]"

    button_login1                       = "//a[@id='dropbtn-login']"
    popup_login                         = "//form[@id='loginForm']"
    form_username                       = "//input[@id='username']"
    form_password                       = "//input[@id='password']"
    button_confirm                      = "//button[contains(text(),'Masuk')]"

    button_newpost                      = "//img[@src='/assets/img/icons/new-post.svg']"

    editor_base                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/textarea[1]"
    editor_baseloc                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/a[1]"
    baseloc_chosen                      = "//div[@class='location-list__name']:://*[contains(text(), ‘central park apartment‘)]"
    editor_base_exec                    = "//button[@id='btn_save_home_timeline']"
    editor_action                       = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]"

    loc_1                               = "//div[@id='locationSebangsa']"
    loc_2                               = "//ul[@class='sc-iuJeZd cMsQfF sc-VigVT gGolQm']"
    loc_3                               = "//div[@id='locationSebangsa']//li[3]"
    loc_4                               = "//div[contains(text(),'central park apartment')]"
    loc_5                               = "//div[@class='location-list__name']"

    editor_container                    = "//textarea[@id='home_timeline_header']"
    editor2_container                   = "//textarea[@id='home_timeline']"
    editor_loc                          = "//div[@class='editor__action sc-bdVaJa iTVXIx']//a[@class='actionable__link actionable__link--location']"
    editor_loc2                         = "//img[@src='/assets/img/icons/action-location.svg']"
    editor_locList                      = "/html/body/div[1]/div[2]/div/div[1]/div/div/div/div/div[3]/div/div[1]/div[2]/div/div/div[2]/ul/li[1]/a/div[1]"
    editor_locField                     = "//*[@id='searchLocation']"
    editor_locField2                    = "//input[@id='Search']"
    editor_stckr_main                   = "//div[@id='container_home_timeline_header']//a[@class='dropbtn actionable__link actionable__link--smiley']"
    editor_stckr_sub                    = "//div[@id='global-modal']//li[5]//a[1]"

    #sticker list
    editor_stckr1                       = "//div[@id='global-modal']//a[15]"
    editor_stckr2                       = "/html/body/div[1]/div[2]/div/div[1]/div/div/div/div/div[3]/div/div[1]/div[3]/div/div/a[15]/img"

    popup                               = "//div[@class='swal-modal']"
    yes_button                          = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"

    editor_menu                         = "//a[@class='post-actions__link post-actions__link--more dropbtn dropdown__toggle']"
    editor_delete                       = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[1]/div[3]/li[1]/div[1]/ul[1]/li[4]/a[1]"
    editor_pop                          = "//div[@class='swal-modal']"
    editor_popquote                     = "//div[@class='swal-modal']"
    editor_yesbtn                       = "//button[@class='swal-button swal-button--confirm swal-button--danger']"
    editor_yesbtnquote                  = "//button[@class='swal-button swal-button--confirm swal-button--danger']"
    editor_execution                    = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/button[1]"
    editor_execution2                   = "//button[@id='btn_save_home_timeline']"
    editor_edit                         = "//a[contains(text(),'Edit Text')]"
    editor_edit_exec                    = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[2]/div[2]/button[1]"
    editor_container2                   = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/textarea[1]"
    attachment                          = "//div[@id='container_home_timeline_header']//input[@name='upload-post']"
    attachment_2                        = "//div[@id='container_home_timeline_header']//input[@name='upload-post']"
    attachment_2a                       = "//input[@name='upload-img']"

    #validation
    card_content                        = "//div[@class='card-content']"
    post_text                           = "//div[@class='card__msg-body card__msg-body--text']"
    post_text_x                         = "/html[1]/body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/p[1]/span[1]"
    post_text2                          = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/p[1]"
    post_component                      = "/html[1]/body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]"
    post_classcomponent                 = "img-stats__wrapper"
    photo_element                       = "//img[@class='card__media-img player-modal']"
    photosets                           = "//div[contains(@class,'photoset clearfix')]"
    photosets_1                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]"
    photosets_2                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[2]"
    photosets_3                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[3]"
    photosets_4                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[4]"

    audio_element                       = "//div[@class='audio-post']"
    audio_duration                      = "//div[@class='audio-post__duration']"
    link_text                           = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/p[1]/a[1]"
    link_element                        = "//div[@class='tl tl--home u-paddingTop0']//div[1]//div[2]//div[1]//div[1]//div[3]//div[1]//div[1]//div[1]//a[1]//img[1]"

    loc_element                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]"
    loc_list                            = "//input[@id='Search']"
    loc1_chosen                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[3]"
    loc_chosen                          = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]"
    loc3_chosen                         = "//*[@id='locationSebangsa']"
    loc_placename                       = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]/span[1]"

    stc_element                         = "//img[@class='sticker']"
    #stc_class                          = "//img[@class='sticker']"

    reshare_element                     = "//p[@class='card__msg-desc small']"

    vote_up                             = "//span[contains(text(),'Upvote')]"
    vote_component                      = "//div[@class='img-stats__wrapper']"
    vote_stat                           = "//a[@title='Upvote']"

    stats                               = "//div[@class='img-stats__wrapper']"

    vote_down                           = "//span[contains(text(),'Downvote')]"
    vote2_component                     = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/a[1]"
    vote2_stat                          = "//li[@class='post-actions__item post-actions__item--vote-down']"
    vote_down_usr                       = "//span[@class='post-actions__item dropdown dropdown--mobile']//li[2]//a[1]"
    vote_down_anon                      = "//a[contains(text(),'Anonymous')]"
    favourite                           = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[1]/div[3]/li[1]/div[1]/ul[1]/li[1]/a[1]"
    unfavourite                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[3]/ul[1]/div[1]/div[3]/li[1]/div[1]/ul[1]/li[1]/a[1]"
    reshare                             = "//a[@title='Reshare']"
    reshare_exec                        = "//a[contains(text(),'Reshare')]"
    quote                               = "//a[@class='reshare-action__link js-toggle']"
    reshare_cancel                      = "//a[contains(text(),'Cancel')]"
    quote_card                          = "//div[@class='card__quote-content']"
    quote_editor                        = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/textarea[1]"
    quote_exec                          = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[3]/div[2]/button[1]"
    quote_postmenu                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[3]/ul[1]/div[1]/div[3]/li[1]/a[1]"
    quote_delete                        = "//a[contains(text(),'Delete')]"

    sebangsa_home                       = "//a[@class='branding__img']//img"
    timeline_body                       = "/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div"
    navigation_bar                      = "/html/body/div[1]/div/div[1]/div/nav"
    timeline_tab                        = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[2]/div[2]/div[3]/a[1]"

    profile                             = "/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/section/div[1]/div[2]/div/a/strong/span[2]"
    edit_profile                        = "/html/body/div[1]/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[2]/div/a"
    usr_name                            = "//input[@id='name']"
    password                            = "//a[contains(text(),'Password')]"
    old_password                        = "//input[@id='password']"
    new_password                        = "//input[@id='new_password']"
    confirm_password                    = "//input[@id='retype_password']"
    save_password                       = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[2]/div[2]/div[1]/div[4]/button[1]"

    avatar                              = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[4]/div[1]/a[1]"
    avatar_sett                         = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[4]/div[1]/div[1]/ul[1]/li[2]/a[1]"
    sett_page                           = "/html/body/div[1]/div/div[2]/div"
    avatar_up                           = "//input[@id='avatar-upload']"
    save_avatar                         = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[2]/div[2]/div[1]/div[3]/div[1]/div[1]/div[3]/button[1]"
    save_prof                           = "//button[@id='btn-loading']"
    button_logout                       = "/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/nav[1]/div[1]/div[4]/div[1]/div[1]/ul[1]/li[4]/a[1]"
    bio                                 = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[2]/div[2]/div[1]/div[7]/div[2]/div[1]/div[1]/textarea[1]"

    create_community                    = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/section[1]/div[2]/a[1]"
    topic                               = "//a[contains(text(),'Tech & Science')]"
    topic_button                        = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/button[1]"
    community_name                      = "//input[@id='name']"
    community_desc                      = "//textarea[@id='description']"
    comm_btn1                           = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[5]/div[1]/button[2]"
    comm_btn2                           = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"
    prvte_comm                          = "//*[@id='visibility2']"
    sett_savebtn                        = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[5]/div[1]/button[1]"
    skip_invtbtn                        = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/a[1]"
    comm_sett_gear                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/a[1]/img[1]"
    comm_settdot                        = "//div[@class='btn dropbtn dropdown sc-TOsTZ gYqiCI']"
    comm_settpage                       = "//a[contains(text(),'Settings Community')]"
    comm_avatar                         = "//input[@id='avatar-upload']"
    save_avatarcomm                     = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[3]/button[1]"
    save_commprof                       = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[9]/div[2]/button[1]"
    comm_home                           = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]"
    delete_comm_button                  = "//a[contains(text(),'Delete Community')]"
    delete_comm_name                    = "//input[@placeholder='Community name']"
    delete_comm_exec                    = "//button[contains(text(),'Delete')]"

    comm_north                          = "//a[@class='group-name']"
    comm_name                           = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/a[2]"
    comm_north_tab                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/a[1]"
    comm_joinbtn                        = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/button[1]"
    comm_popup                          = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]"
    comm_join_pass                      = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/input[1]"
    comm_join_exec                      = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[7]/button[2]"
    comm_leave_pop                      = "/html[1]/body[1]/div[3]/div[1]"
    comm_leave_exec                     = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"

    comm_editor                         = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/textarea[1]"
    comm_editorexec                     = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/button[1]"
    comm_text                           = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]"
    comm_text2                          = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]"
    comm_editor_option                  = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[1]/div[3]/li[1]/a[1]"
    comm_post_delete                    = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[1]/div[3]/li[1]/div[1]/ul[1]/li[5]/a[1]"
    comm_post_delete_mbr                = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[1]/div[3]/li[1]/div[1]/ul[1]/li[4]/a[1]"
    comm_attch                          = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/a[1]/input[1]"
    comm_attch2                         = "//input[@name='upload-img']"

    comm_reply                          = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[1]/li[1]/a[1]/span[1]"
    comm_reply_editor                   = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/textarea[1]"
    comm_reply_role                     = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/div[1]"
    comm_role_acc                       = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]/div[1]"
    comm_role_comm                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/div[1]"
    comm_reply_exec                     = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[1]/div[2]/div[1]/div[1]/div[3]/div[2]/button[1]"
    comm_reply_opt                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[3]/ul[1]/li[1]/div[1]/div[2]/div[4]/div[1]/a[1]/img[1]"
    comm_reply_opt2                     = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[3]/ul[1]/li[1]/div[1]/div[3]/div[4]/div[1]/a[1]/img[1]"
    comm_reply_delete                   = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[3]/ul[1]/li[1]/div[1]/div[2]/div[4]/div[1]/div[1]/ul[1]/div[1]/li[2]/a[1]"
    comm_reply_delete2                  = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[3]/ul[1]/li[1]/div[1]/div[3]/div[4]/div[1]/div[1]/ul[1]/div[1]/li[2]/a[1]"
    comm_reply_validation               = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[4]/div[1]/div[1]/div[3]/ul[1]/li[1]/div[1]/a[1]"

    comm_member                         = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[2]/div[1]/a[1]"
    comm_member_sett                    = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]"
    comm_label_validation               = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]"

    senggolan_create                    = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/a[1]"
    senggolan_category                  = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/select[1]"
    senggolan_project                   = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/select[1]/option[9]"
    senggolan_title                     = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[3]/div[2]/input[1]"
    senggolan_desc                      = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[4]/div[2]/textarea[1]"
    senggolan_attc1                     = "//div[@class='senggolan-create__attachment']//div[1]//input[1]"
    senggolan_attc2                     = "//div[@class='col-12_sm-12']//div[2]//input[1]"
    senggolan_attc3                     = "//div[@class='senggolan-create__group grid col-12']//div[3]//input[1]"
    senggolan_attc4                     = "//body//div[@id='site-container']//div//div[4]//input[1]"
    senggolan_pass                      = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/input[1]"
    senggolan_exec                      = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[4]/div[1]/div[1]/div[1]/button[2]"
    senggolan_option                    = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[5]/div[1]/ul[1]/div[1]/div[1]/li[1]/a[1]"
    senggolan_header                    = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]"
    senggolan_title_valid               = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/h2[1]"
    senggolan_delete                    = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[5]/div[1]/ul[1]/div[1]/div[1]/li[1]/div[1]/ul[1]/div[1]/li[2]/a[1]"
    senggolan_delete_exec               = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"

    qck_pass1                           = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/input[1]"
    qck_pass2                           = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/input[2]"
    qck_pass3                           = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/input[3]"
    qck_pass4                           = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/input[4]"
    qck_pass5                           = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/input[5]"

    comm_room_sidebar                   = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/div[1]/ul[1]/li[3]/a[1]"
    comm_room_add                       = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[1]/a[2]"
    comm_room_name                      = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]"
    comm_room_name2                     = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/a[1]"
    comm_room_pass                      = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/input[1]"
    comm_room_hint                      = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/input[1]"
    comm_room_save                      = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[4]/button[2]"
    comm_room_save_wpass                = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[5]/button[2]"
    comm_room_editorlist                = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]"
    comm_room_pop_editorlist            = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]"

    comm_room_list                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/ul[1]"
    comm_room_editorname                = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/a[1]"
    comm_room_pop_editorname            = "/html[1]/body[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]"
    comm_room_option                    = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[1]"
    comm_room_delete                    = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[2]/ul[1]/li[2]/a[1]"



    comm_set_officer                    = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/ul[1]/a[1]"
    comm__officer_popup                 = "//div[@class='swal-modal']"
    comm_officer_exec                   = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"
    comm_officer_labelinput             = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/input[1]"
    comm_officer_labexec                = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[3]/button[1]"
    comm_officer_validate               = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]"
    comm_officer_unset                  = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/ul[1]/a[1]"
    comm_officer_unsetexec              = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"

    comm_set_admin                      = "/html[1]/body[1]/div[1]/div[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/ul[1]/li[1]/a[1]"
    comm__admin_popup                   = "//div[@class='swal-modal']"
    comm_admin_exec                     = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"
    comm_unsetadmin_exec                = "/html[1]/body[1]/div[3]/div[1]/div[4]/div[2]/button[1]"
